import type { Metadata } from 'next'
import { pretendard } from './fonts'
import './globals.css'
import { Sidebar } from '@/components/sidebar'
import { cn } from '@/utils/cn'
import { Header } from '../components/header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" className={pretendard.variable}>
      <body className={cn(pretendard.className)}>
        <div className="flex h-screen overflow-hidden">
          <Sidebar className="fixed top-0" />
          <div className="w-full relative pl-[106px]">
            <Header className="sticky top-0" />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
