import type { Metadata } from 'next'
import { pretendard } from './fonts'
import './globals.css'
import { Sidebar } from '@/components/sidebar'
import { cn } from '@/utils/cn'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" className={pretendard.variable}>
      <body className={cn(pretendard.className)}>
        <div className="flex">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  )
}
